FROM php:8.1-fpm

# Copy composer.lock and composer.json into the working directory
COPY composer.lock composer.json /var/www/html/

# Set working directory
WORKDIR /var/www/html/

# Install dependencies for the operating system software
RUN apt-get update && apt-get install -y zip unzip openssl cron \
libxml2-dev libzip-dev curl libmcrypt-dev libpng-dev libonig-dev sendmail-bin sendmail 

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs npm

# Install extensions for php
RUN docker-php-ext-install pdo pdo_mysql zip intl mbstring bcmath gd opcache	

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer (php package manager)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer  
ENV COMPOSER_ALLOW_SUPERUSER 1

# Copy existing application directory contents to the working directory
COPY . /var/www/html

# Deploy JavaScript (frontend)
RUN npm install && npm run build 

# Deploy PHP (backend)
RUN composer install --no-interaction --no-progress --optimize-autoloader  

COPY .env.dev .env

RUN php deploy

# Expose port 9000 and start php-fpm server (for FastCGI Process Manager)
EXPOSE 9000
CMD ["php-fpm"]