version: '3.7'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    db:
        image: mariadb:11.0.2
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: biznisbox
            MYSQL_ROOT_PASSWORD: biznisbox
            MYSQL_USER: biznisbox
            MYSQL_PASSWORD: biznisbox
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql/
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
