import tailwindcssPrimeUI from 'tailwindcss-primeui'
export default {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{vue,js,ts}',
        './resources/js/presets/**/*.{vue,js,ts}',
        './node_modules/primevue/**/*.{vue,js,ts,jsx,tsx,css}',
        './resources/css/**/*.css',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: 'var(--primary-600)',
                'primary-contrast': 'var(--surface-50)',
                'primary-emphasis': 'var(--primary-700)',
                'border-surface': 'var(--surface-200)',
                'bg-emphasis': 'var(--surface-50)',
                'bg-highlight': 'var(--surface-100)',
                'bg-highlight-emphasis': 'var(--surface-300)',
                'text-color': 'var(--primary-900)',
                'text-color-emphasis': 'var(--primary-500)',
                'text-muted-color': 'var(--surface-600)',
                'text-muted-color-emphasis': 'var(--surface-500)',
                'primary-0': 'var(--primary-0)',
                'primary-50': 'var(--primary-50)',
                'primary-100': 'var(--primary-100)',
                'primary-200': 'var(--primary-200)',
                'primary-300': 'var(--primary-300)',
                'primary-400': 'var(--primary-400)',
                'primary-500': 'var(--primary-500)',
                'primary-600': 'var(--primary-600)',
                'primary-700': 'var(--primary-700)',
                'primary-800': 'var(--primary-800)',
                'primary-900': 'var(--primary-900)',
                'primary-950': 'var(--primary-950)',
                'surface-0': 'var(--surface-0)',
                'surface-50': 'var(--surface-50)',
                'surface-100': 'var(--surface-100)',
                'surface-200': 'var(--surface-200)',
                'surface-300': 'var(--surface-300)',
                'surface-400': 'var(--surface-400)',
                'surface-500': 'var(--surface-500)',
                'surface-600': 'var(--surface-600)',
                'surface-700': 'var(--surface-700)',
                'surface-800': 'var(--surface-800)',
                'surface-900': 'var(--surface-900)',
                'surface-950': 'var(--surface-950)',
                'blue-0': 'var(--blue-0)',
                'blue-50': 'var(--blue-50)',
                'blue-100': 'var(--blue-100)',
                'blue-200': 'var(--blue-200)',
                'blue-300': 'var(--blue-300)',
                'blue-400': 'var(--blue-400)',
                'blue-500': 'var(--blue-500)',
                'blue-600': 'var(--blue-600)',
                'blue-700': 'var(--blue-700)',
                'blue-800': 'var(--blue-800)',
                'blue-900': 'var(--blue-900)',
                'blue-950': 'var(--blue-950)',
                'green-0': 'var(--green-0)',
                'green-50': 'var(--green-50)',
                'green-100': 'var(--green-100)',
                'green-200': 'var(--green-200)',
                'green-300': 'var(--green-300)',
                'green-400': 'var(--green-400)',
                'green-500': 'var(--green-500)',
                'green-600': 'var(--green-600)',
                'green-700': 'var(--green-700)',
                'green-800': 'var(--green-800)',
                'green-900': 'var(--green-900)',
                'green-950': 'var(--green-950)',
                'red-0': 'var(--red-0)',
                'red-50': 'var(--red-50)',
                'red-100': 'var(--red-100)',
                'red-200': 'var(--red-200)',
                'red-300': 'var(--red-300)',
                'red-400': 'var(--red-400)',
                'red-500': 'var(--red-500)',
                'red-600': 'var(--red-600)',
                'red-700': 'var(--red-700)',
                'red-800': 'var(--red-800)',
                'red-900': 'var(--red-900)',
                'red-950': 'var(--red-950)',
                'orange-0': 'var(--orange-0)',
                'orange-50': 'var(--orange-50)',
                'orange-100': 'var(--orange-100)',
                'orange-200': 'var(--orange-200)',
                'orange-300': 'var(--orange-300)',
                'orange-400': 'var(--orange-400)',
                'orange-500': 'var(--orange-500)',
                'orange-600': 'var(--orange-600)',
                'orange-700': 'var(--orange-700)',
                'orange-800': 'var(--orange-800)',
                'orange-900': 'var(--orange-900)',
                'orange-950': 'var(--orange-950)',
            },
        },
    },
    plugins: [tailwindcssPrimeUI],
}
