---
name: Bug Report
description: File a bug report 🐛
title: '🐛[Bug]: '
labels:
    - 🐛bug
    - 👁️triage
assignees:
    - patik123
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: A bug happened!
      validations:
          required: true
    - type: input
      id: version
      attributes:
          description: Which version of BiznisBox did you use
          placeholder: Version
          label: Version
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: What browsers are you seeing the problem on?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
              - All
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be
              automatically formatted into code, so no need for backticks.
          render: shell
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of
              Conduct](https://github.com/biznisbox/biznisbox/blob/main/CODE_OF_CONDUCT)
          options:
              - label: "I agree to follow this project's Code of Conduct"
                required: true
