name: 'Build development Docker image'
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build Docker image (development)
              run: docker compose -f docker-compose.yml build 
            - name: Tag Docker image (development)
              run: docker tag docker-compose_development ghcr.io/biznisbox/biznisbox:development
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Docker image (development)
              run: docker compose -f docker-compose.yml push