name: 'Build production Docker image'
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build Docker image (development)
              run: docker compose -f docker-compose.yml build
